rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
gemfile:
  - Gemfile.devise12
  - Gemfile.devise13
  - Gemfile.devise14
  - Gemfile.devise15
  - Gemfile.devise20
  - Gemfile.devise21
script: "bundle exec rake spec"

