rvm:
  - 2.0.0
  - 2.1.2
  - 2.2.4
  - 2.3.0
gemfile:
  - Gemfile.devise12
  - Gemfile.devise13
  - Gemfile.devise14
  - Gemfile.devise15
  - Gemfile.devise20
  - Gemfile.devise21
  - Gemfile.devise30
script: "bundle exec rake spec"

